# Generated by Django 3.2.4 on 2021-06-18 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=30)),
                ('phone', models.IntegerField(unique=True)),
                ('sal', models.FloatField()),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('deptno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.dept')),
            ],
        ),
    ]
